name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'   # Roz raat 12 baje chalega
  workflow_dispatch:       # Manually bhi run kar sakte ho

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run daily commit script
        run: |
          import subprocess, datetime

          now = datetime.datetime.now()
          msg = f"Automated commit on {now.strftime('%Y-%m-%d %H:%M:%S')}"

          # log.txt me commit time likhna
          with open("log.txt", "a") as f:
              f.write(msg + "\n")

          # Git config
          subprocess.run(["git", "config", "user.name", "chsabii"])
          subprocess.run(["git", "config", "user.email", "choudarysohaib786@gmail.com"])

          # Changes add & commit
          subprocess.run(["git", "add", "log.txt"])
          result = subprocess.run(["git", "commit", "-m", msg])

          # Agar koi change na mila to commit skip ho jaye
          if result.returncode != 0:
              print("No changes to commit")

          # Push to repo
          subprocess.run(["git", "push"])
        shell: python
