name: Daily Pattern Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at 12:00 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pattern-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure log file exists
        run: touch log.txt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Write pattern script to file
        shell: bash
        run: |
          cat > pattern_commit.py << 'PY'
          import datetime
          import subprocess

          PATTERN = [
              [10,10,10,10,10, 0, 10,  5, 10,  5, 10,  5,  0, 10,10,10,10,10, 0, 10, 10,10,10,10, 0,  5, 10,10,10, 5,  0, 10,  0, 10,  0, 10,10,10,10,10, 0, 10,10,10,10,10, 0, 10,10,10,10,10],
              [10, 0,  0,  0,10, 0, 10, 10,  0, 10,  0, 10, 0, 10, 0,  0,  0,10, 0, 10,  0,  0,  0,10, 0,  5,  0,  0, 10, 0, 10,  0, 10,  0, 10, 0,  0,  0,10, 0, 10,  0,  0,  0,10, 0, 10,  0,  0,  0,10],
              [10, 0,  0,  0,10, 0, 10, 10,  0, 10,  0, 10, 0, 10, 0,  0,  0,10, 0, 10, 10, 10,10,10, 0,  5,  0,  0, 10, 0, 10,  0, 10,  0, 10, 0,  0,  0,10, 0, 10, 10, 10,10,10, 0, 10,  0,  0,  0,10],
              [10, 0,  0,  0,10, 0, 10, 10,  0, 10,  0, 10, 0, 10, 0,  0,  0,10, 0, 10,  0,  0,  0,10, 0,  5,  0,  0, 10, 0, 10,  0, 10,  0, 10, 0,  0,  0,10, 0, 10,  0,  0,  0,10, 0, 10,  0,  0,  0,10],
              [10, 0,  0,  0,10, 0, 10, 10,  0, 10,  0, 10, 0, 10, 0,  0,  0,10, 0, 10, 10, 10,10,10, 0,  5,  0,  0, 10, 0, 10,  0, 10,  0, 10, 0,  0,  0,10, 0, 10, 10, 10,10,10, 0, 10,  0,  0,  0,10],
              [10, 0,  0,  0,10, 0, 10, 10,  0, 10,  0, 10, 0, 10, 0,  0,  0,10, 0, 10,  0,  0,  0,10, 0,  5,  0,  0, 10, 0, 10,  0, 10,  0, 10, 0,  0,  0,10, 0, 10,  0,  0,  0,10, 0, 10,  0,  0,  0,10],
              [10,10,10,10,10, 0, 10,  5, 10,  5, 10,  5, 0, 10,10,10,10,10, 0, 10, 10,10,10,10, 0,  5, 10,10,10, 5, 0, 10,  0, 10,  0, 10,10,10,10,10, 0, 10,10,10,10,10, 0, 10,10,10,10,10],
          ]

          today = datetime.date.today()
          year_start = datetime.date(today.year, 1, 1)
          week_num = (today - year_start).days // 7  # 0-based week idx
          day_num = today.weekday()  # 0=Mon ... 6=Sun

          # Always at least one commit so run shows up in dashboard
          commits_today = 1
          if day_num < len(PATTERN) and week_num < len(PATTERN[0]):
              commits_today = PATTERN[day_num][week_num] or 1

          print(f"Week: {week_num}, Day: {day_num}, Commits today: {commits_today}")

          # Set repo-local identity (no --global needed)
          subprocess.run(["git", "config", "user.name", "chsabii"])
          subprocess.run(["git", "config", "user.email", "choudarysohaib786@gmail.com"])

          for i in range(commits_today):
              with open("log.txt", "a") as f:
                  f.write(f"{datetime.datetime.now()} - Week {week_num}, Day {day_num}, Commit {i+1}\n")
              subprocess.run(["git", "add", "log.txt"])
              subprocess.run(["git", "commit", "-m", f"Pattern commit {i+1} - Week {week_num}, Day {day_num}"])

          subprocess.run(["git", "push"])
          PY

      - name: Run Python script
        run: python pattern_commit.py
