name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 12:00 AM UTC
  workflow_dispatch:     # Manual run bhi allowed

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make a change
      run: |
        echo "$(date) - daily update" >> log.txt
        git config --global user.name "chsabii"
        git config --global user.email "choudarysohaib786@gmail.com"
        git add log.txt
        git commit -m "Daily update: $(date)"
        git push
